package com.epro.pos.mvp.model.bean

data class CashierRecon(val bankCardAmount: String,
                        val bankCardBackAmount: String,
                        val bankCardBackCount: String,
                        val bankCardCount: String,
                        val bankCardSaleAmount: String,
                        val bankCardSaleCount: String,
                        val cashAmount: String,
                        val cashBackAmount: String,
                        val cashBackCount: String,
                        val cashCount: String,
                        val cashSaleAmount: String,
                        val cashSaleCount: String,
                        val cashierId: String,
                        val cashierName: String,
                        val createTime: String,
                        val creditCardAmount: String,
                        val creditCardBackAmount: String,
                        val creditCardBackCount: String,
                        val creditCardCount: String,
                        val creditCardSaleAmount: String,
                        val creditCardSaleCount: String,
                        val firstSaleTime: String,
                        val id: String,
                        val lastSaleTime: String,
                        val shopId: String,
                        val shopName: String,
                        val statementId: String,
                        val totalAmount: String,
                        val totalCount: String,
                        val wxAmount: String,
                        val wxBackAmount: String,
                        val wxBackCount: String,
                        val wxCount: String,
                        val wxSaleAmount: String,
                        val wxSaleCount: String,
                        val zfbAmount: String,
                        val zfbBackAmount: String,
                        val zfbBackCount: String,
                        val zfbCount: String,
                        val zfbSaleAmount: String,
                        val zfbSaleCount: String,
                        val faceAmount: String,
                        val faceBackAmount: String,
                        val faceBackCount: String,
                        val faceCount: String,
                        val faceSaleAmount: String,
                        val faceSaleCount: String,
                        val saleTotalCount: String?,
                        val saleTotalAmount: String?,
                        val backTotalCount: String?,
                        val backTotalAmount: String?){


    data class PayModeCashierRecon(val payModeName:String,val saleCount:String,val saleAmount:String,val refundCount:String,val refundAmount:String,val totalAmount:String="0")
}

