package com.epro.pos.mvp.model.bean

data class OrderRecord(val cashierId: String,
                       val cashierName: String,
                       val createTime: String,
                       val channel: String?,
                       val orderActualAmount: String,
                       val orderId: String,
                       val orderSn: String,
                       val orderStatus: Int,
                       val orderType: Int,
                       val originalOrderSn: String,
                       val payType: Int,
                       val puserId: String,
                       val remark: String,
                       val shopId: String,
                       val shopName: String,
                       val shopMobile: String?,
                       val tradeType: Int,
                       val productCount: Int,
                       val deliveryType: Int,
                       val address: String?,
                       val consignee: String?,
                       val paySn: String?,
                       val mobile: String?,
                       val orderCancelReason: String?,
                       val reimburseStatus: Int?,
                       val orderClosedTime: String?,
                       val products: ArrayList<OrderProduct>?,
                       val courierMobile: String?,
                       val courierName: String?,
                       val logisticsFee: Int?,
                       val orderDesc: String?,
                       val pickUpAdress: String?,
                       val refundPaySn: String?,
                       val pickUpTime: String?) {
}


