package com.epro.pos.mvp.model.bean

data class ProductDetail(val approvalStatus: Int,
                         val brandId: String,
                         val brandName: String,
                         val buyingPrice: String,
                         val compressPicUrl: String,
                         val deliveryDistance: String,
                         val deliveryMode: String,
                         val frozenDesc: String,
                         val goodsBinding: Int,
                         val goodsCompressPriUrl: String,
                         val goodsCompressPriUrl1: String,
                         val goodsCompressPriUrl2: String,
                         val goodsCompressPriUrl3: String,
                         val goodsCompressPriUrl4: String,
                         val goodsDesc: String,
                         val goodsID: String,
                         val goodsName: String,
                         val goodsPicUrl: String,
                         val goodsPicUrl1: String,
                         val goodsPicUrl2: String,
                         val goodsPicUrl3: String,
                         val goodsPicUrl4: String,
                         val goodsTypeId: String,
                         val goodsTypeName: String,
                         val goodsUnitId: String,
                         val goodsUnitName: String,
                         val onlineSalesPrice: String,
                         val productBarCode: String,
                         val productCombinationList: ArrayList<Any?>,
                         val productId: String,
                         val productNumber: Int,
                         val productPicUrl: String,
                         val productStatus: String,
                         val retailPrice: String,
                         val shoppingMallName: String,
                         val specificationsValueIds: String,
                         val specificationsValueNames: String,
                         val status: Int,
                         val stockEarlyNum: Int) {
  
}